alter table orders
  add column if not exists sender_name text,
  add column if not exists sender_tin text,
  add column if not exists sender_country text,
  add column if not exists sender_address text,
  add column if not exists sender_bank text,
  add column if not exists sender_account text,
  add column if not exists sender_currency text,
  add column if not exists receiver_name text,
  add column if not exists receiver_tin text,
  add column if not exists receiver_country text,
  add column if not exists receiver_address text,
  add column if not exists receiver_bank text,
  add column if not exists receiver_account text,
  add column if not exists receiver_currency text,
  add column if not exists payment_purpose text,
  add column if not exists payment_amount text,
  add column if not exists payment_currency text,
  add column if not exists tnved text,
  add column if not exists terms text,
  add column if not exists deadline date,
  add column if not exists jurisdiction text,
  add column if not exists bank_restrictions text,
  add column if not exists created_at timestamp with time zone default now(),
  add column if not exists updated_at timestamp with time zone default now(); 