create table if not exists orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) not null,
  status text default 'draft',
  date date default now(),
  amount numeric,
  currency text,
  recipient text,
  sender_name text,
  sender_tin text,
  sender_country text,
  sender_address text,
  sender_bank text,
  sender_account text,
  sender_currency text,
  receiver_name text,
  receiver_tin text,
  receiver_country text,
  receiver_address text,
  receiver_bank text,
  receiver_account text,
  receiver_currency text,
  payment_purpose text,
  payment_amount text,
  payment_currency text,
  tnved text,
  terms text,
  deadline date,
  jurisdiction text,
  bank_restrictions text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists user_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) unique not null,
  name text not null,
  company text not null,
  created_at timestamp with time zone default now()
); 